Update to beta version
Features
- Statics functions can be called without init function and only these functions and the init command can be called at the beginning
- The scrollTo function have now more precision
- Added scrollAPI.debug, if this var is defined to true you will see all debug message: usefull to report a new issue

Code cleanup
- Remove useless else
- Remove useless functions
- Rename api.window to api.isWindow
- The compatibility check is defined by 'function' in object and not object.function
- Added 'use strict' to improve realiability of code

Fixes
- Polyfill not override other function and work only in scrollAPI interface
- [Uncaught TypeError: api.isScrollable is not a function] is now in self interface
- Support IE5+ for scrollTop/Left, navigator userAgent, prefix for CSS, api.isInDOM function and the window.event
- Support old firefox versions for wheel event
- Support old opera versions for navigator userAgent
- Support passive event and patch the default value defined by Chromium 73+
- Patch for Chromium: outline at focus element and the value defined for config.scrollTo when user refresh the page

Performance
- Added scrollAPI@compatibility for save compatibility data and scrollAPI@polyfill to support olds browsers
- The array object are now simple array with the indexOf function
- The api.config loop is now a while loop to gain some speed
- The module avoid to recall base function like isPhone, isBrowser("Trident") like cache storage...